baseurl = "https://blank71.github.io/blog/"
title = "blank71 blog"
author = "blank71"
canonifyurls = true
paginate = 10
theme = "aether"
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"